<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-ProjectCenturion.WorkerFunctions-2eeb8b00-0665-4dfe-b0d5-32b610b55258</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" Version="8.5.7" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.7" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ProjectCenturion.Leads\ProjectCenturion.Leads.csproj" />
      <ProjectReference Include="..\ProjectCenturion.ServiceDefaults\ProjectCenturion.ServiceDefaults.csproj" />
    </ItemGroup>
</Project>
