@HostAddresss = http://localhost:5111

POST {{HostAddresss}}/api/v1/leadingestion?leadSource={{$random.uuid}}
Accept: application/json
Content-Type: application/json

{
  "firstName": "Rick",
  "lastName": "Test"
}

###
